on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.3.967'
      - uses: actions/cache@v2
        with:
          path: '~/.m2'
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: clojure -M:cljfmt check
      - run: clojure -M:clj-kondo
      - run: clojure -M:test
  release:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.3.967'
      - uses: actions/cache@v2
        with:
          path: '~/.m2'
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Create tag
        id: create-tag
        run: echo "::set-output name=tag::$(date +v%Y.%m.%d.%H%M)"
      - name: Configure version
        run: |
          mkdir -p resources/META-INF/app
          echo "version=${{ steps.create-tag.outputs.tag }}" > resources/META-INF/app/config.properties
      - name: Build artifacts
        run: make target/plv-portal.jar target/plv-reveal.jar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: '${{ steps.create-tag.outputs.tag }}'
          files: |
            target/plv-portal.jar
            target/plv-reveal.jar
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
