on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.1.716'
      - run: |
          clojure -M:cljfmt check
          clojure -M:clj-kondo
          clojure -M:test
